### ISSUE TITLE
Lowercase l that looks different from uppercase I

### ISSUE THREAD

**Issue by rben01** [erikdkennedy/figtree#20] opened 2022-12-28 16:58 UTC
It would be great to have a stylistic set (CSS `font-feature-settings`) that adds a hook to the lowercase l to differentiate it from the uppercase I. Having the two characters look the same is ok in some contexts but confusing in others, so it would be great to toggle a flag to be able to differentiate them.

**Comment by erikdkennedy** [comment] 2022-12-28 17:06
Noted and do plan on adding at some point 👍 

Is this issue blocking you from using Figtree in a design?

**Comment by rben01** [comment] 2022-12-28 17:08
Thanks! It's not blocking me, I just think it'd be nice to have in general.

**Comment by naiyerasif** [comment] 2023-02-14 18:08
I'd also suggest a disambiguation for zero and uppercase O as well. A slashed or dotted zero should be good alternative for this.

**Comment by vimalkvn** [comment] 2023-03-24 17:23
Would be nice to have them differentiated. The problem is apparent in words like 'Illusion' or 'Install' when used in headlines.
Thanks for your work. Using the font as a default on desktop. Looks real nice!

**Comment by erikdkennedy** [comment] 2023-04-05 17:46
Fixed in newest version 👍

**Closed by erikdkennedy** 2023-04-05 17:46 UTC

**Comment by rben01** [comment] 2023-04-05 18:05
TYSM! Would it be possible to add character variants (`cvXX`) for the individual letters l, I, and 0 as well?

**Comment by erikdkennedy** [comment] 2023-04-05 18:22
`I` and `l` make more sense as a set, IMO. So that leaves individual control over `0`. Is that level of granularity useful for something you're thinking of, or are you just trying to keep your options open?

**Comment by rben01** [comment] 2023-04-05 18:29
You pretty much nailed it. I would probably enable disambiguation for both `l` and `I`, but not 0 — I like my 0‘s unslashed, and they're distinct enough from O as it is.
